### ISSUE TITLE
The cljdoc page for alda-clj is broken

### ISSUE THREAD

**Issue by UlyssesZh** [daveyarwood/alda-clj#9]
See https://cljdoc.org/builds/46043.

**Comment by daveyarwood** [comment]
I'm glad you reported this, because it turns out that when I deployed alda-clj 0.3.0, it was using a stale pom.xml, which resulted in missing dependencies!

I released alda-clj 0.3.3 today, which fixes the dependency issues and gets the cljdoc build working.

https://cljdoc.org/d/io.djy/alda-clj/0.3.3/doc/readme
